package org.nkjmlab.sorm4j.util.h2;

import java.io.File;
import org.nkjmlab.sorm4j.util.h2.sql.H2CsvReadSql;
import org.nkjmlab.sorm4j.util.table_def.TableWithDefinition;

public interface H2TableWithDefinition<T> extends TableWithDefinition<T>, H2Table<T> {

  default H2CsvReadSql.Builder csvReadSqlBuilder(File csvFile) {
    return H2CsvReadSql.builder(csvFile).setColumns(getTableMetaData().getNotAutoGeneratedColumns());
  }
}
